### ISSUE TITLE
trying to  make it run with newer go and recent otto vm version

### ISSUE THREAD

**Issue by phaus** [tiborvass/go-jsx#1]
HI @tiborvass .

Although this repository looks pretty abandoned, I think I will give it a try.
I just forked it and trying to make it work again.

So I already added a mod file and fixed some API stuff regarding Otto VM.
But If I am using the build binary, it just outputs the same jsx, that is content of the example.jsx.

I will do a little bit more debugging, but maybe you have a pointer for me? 

Thx 🙏

**Comment by tiborvass** [comment]
@phaus 

Wow! Thank you! Yes I hacked this together a long time ago :) I managed to debug it: looks like the position column in the error is off by one. So:
```Go
if pos.Column == err.Position.Column && pos.Line == err.Position.Line && ...
```
should become
```Go
if pos.Column == err.Position.Column-1 && pos.Line == err.Position.Line && ...
```

Please feel free to send the PR will gladly merge it!

**Comment by phaus** [comment]
Nice! It works!

I just created the PR.
Would you be interested in another hobby project regarding JSX, Otto and Go? Are you available in the gophers slack workspace?

**Comment by tiborvass** [comment]
@phaus interested to hear about it! Responded on slack.
