### ISSUE TITLE
React.render is deprecated. 

### ISSUE THREAD

**Issue by stevenanthonyrevo** [tiborvass/go-jsx#4]
Hi all, 

I was using `React JS - 0.14.9v` with `React-dom - 0.14.9v` and received a warning in the browser after compiling a go-jsx file to js. It generated a file with `react.render` and this function looks to be deprecated now.   

```
Warning: React.render is deprecated. Please use ReactDOM.render from require('react-dom') instead.
```

Let me know if there is anything I can do, to get upgraded to 15.0.0 react js and above.

**Comment by tiborvass** [comment]
@stevenanthonyrevo go-jsx doesn't generate `React.render` calls, only `React.createElement` and `React.__spread` calls. If you had `React.render` calls in your jsx file, you've got to fix them first. Closing but let me know if I misunderstood.
